// Restrained field-log palette: jade and ember supported by legible neutral tones.
export const GENRE_COLORS: Record<string, string> = {
  'k-pop': '#E76F45',
  'k-hip-hop': '#B65B3D',
  'k-rnb': '#C98B72',
  'k-rock': '#8F4434',
  house: '#0F6259',
  techno: '#244C47',
  trap: '#D27A45',
  dubstep: '#5C514A',
  'future-bass': '#3D8278',
  'electro-pop': '#A76E5A',
  downtempo: '#76938B',
  'progressive-house': '#416F69',
  midtempo: '#78665E',
  'hip-hop': '#A9733F',
  rnb: '#8F7868',
  'alt-rnb': '#A99786',
  rock: '#8A5144',
  'alt-rock': '#B46751',
  'indie-pop': '#668B76',
  'indie-rock': '#456F59',
  pop: '#C47A67',
  'alt-pop': '#AE8A7E',
  country: '#A9864F',
  latin: '#C86643',
  afrobeats: '#778550',
  'j-pop': '#B87369',
  'c-pop': '#9D7770',
  bass: '#596E70',
  'melodic-bass': '#4D5F66',
  electronic: '#2F746C',
  other: '#7B7D77',
}

// Meta tags to ignore for genre classification
export const META_TAGS = new Set([
  'solo',
  'group',
  'band',
  'duo',
  'dj',
  'dj-duo',
  'dj-group',
  'collab',
  'producer',
  'english',
  'korean',
  'japanese',
  'french',
  'spanish',
  'mandarin',
  'bilingual',
  'instrumental',
  'us',
  'uk',
  'south-korea',
  'japan',
  'china',
  'france',
  'canada',
  'australia',
  'sweden',
  'germany',
  'belgium',
  'norway',
  'haiti',
  'indonesia',
  'nigeria',
  'colombia',
  'spain',
  'puerto-rico',
  'new-zealand',
  'hong-kong',
  'lebanon',
  'bangladesh',
  'multi-national',
  'korean-american',
  'vietnamese-american',
  'festival',
  'electronic',
  'edm',
  'girl-group',
  'boy-group',
])

// Genre hierarchy - first match wins (order matters!)
export const GENRE_PRIORITY: string[] = [
  // Korean Specific (highest priority)
  'k-pop',
  'k-hip-hop',
  'k-rnb',
  'k-rock',
  // Specific Electronic
  'techno',
  'house',
  'trap',
  'dubstep',
  'future-bass',
  'hardstyle',
  'midtempo',
  'downtempo',
  'electro-pop',
  'progressive-house',
  'uk-garage',
  'disco-house',
  'electro-house',
  'melodic-house',
  'melodic-bass',
  'bass',
  'indietronica',
  'live-electronic',
  'future-funk',
  'nu-jazz',
  'synth-pop',
  'dancehall',
  // General Genres
  'hip-hop',
  'rnb',
  'alt-rnb',
  'rock',
  'alt-rock',
  'pop-rock',
  'pop-punk',
  'emo',
  'metalcore',
  'indie-pop',
  'indie-rock',
  'pop',
  'alt-pop',
  'country',
  'soul',
  'soul-pop',
  'funk',
  'afrobeats',
  'latin',
  'reggaeton',
  'j-pop',
  'c-pop',
]

// Colors for treemap (balanced taupe-friendly palette)
export const TREEMAP_COLORS = {
  festival: '#0F6259',
  venue: '#E76F45',
}
